### ISSUE TITLE
Ili9341 vs spi_master.h

### ISSUE THREAD

**Issue by crmabs** [OLIMEX/MOD-LCD2.8RTP#2]
Hi,
Good news for the ESP-IDF fanatics: the famous SPI+DMA example works with you product if you initalize the GPIO pins properly. PIN_NUM_DC needs especially to be treated fair otherwise the screen stays white.
  Nothing fancy, just something like this:

```
  gpio_config_t io_conf;
  io_conf.intr_type = (gpio_int_type_t)GPIO_PIN_INTR_DISABLE;
  io_conf.mode = GPIO_MODE_OUTPUT;
  io_conf.pin_bit_mask = 1<<PIN_NUM_DC;
  io_conf.pull_down_en = (gpio_pulldown_t)GPIO_PULLDOWN_DISABLE;
  io_conf.pull_up_en = (gpio_pullup_t)GPIO_PULLUP_DISABLE;
  
  esp_err_t res;
  res = gpio_config(&io_conf);
  ESP_ERROR_CHECK(res); 
```
https://github.com/espressif/esp-idf/tree/master/examples/peripherals/spi_master

I'm aware of the fact that the above mentioned repo is handled by Espressif, this message is just sharing the solution. Tested on Olimex Esp-Evb board + MOD-LCD2.8RTP.

Have a nice day!

**Comment by DanKoloff** [comment]
Nice, thanks. Hope this information doesn't get lost!

We also have support for the display in our Arduino package, as shown here: https://github.com/OLIMEX/MOD-LCD2.8RTP/tree/master/SOFTWARE

And we also tested NES emulator here:

https://www.youtube.com/watch?v=v96blCp6uOM

**Comment by crmabs** [comment]
So far I didn't dare to post a issue in the esp-idf repo because I have a feeling (not tested yet) that the issue is related to the fact that the Olimex Esp-Evb has some extra electronics wired on those lines and not directly connected with a plain wire.

Yes, the Arduino example works flawlessly no doubt. That gave me hope on the first place. 
Btw, it would be nice to have a jumper for the backlight. (not soldered)  Or some detailed docs, the schematic is definitive that's for sure, but not always simple to figure out.
 Food for thought.
